### ISSUE TITLE
rss源推荐

### ISSUE THREAD

**Issue by ttttmr** [firmianay/yarb#4]
先知 https://xianzhi2rss.xlab.app/feed.xml
公众号 https://wechat2rss.xlab.app/posts/list

**Comment by firmianay** [comment]
可以做一个方便导入的opml吗

**Comment by ttttmr** [comment]
因为收录的不只是安全的，有整理一部分安全的公众号的集合，一些个人的安全公众号没有放在集合里

https://github.com/ttttmr/wechat2rss

[部分安全相关公众号Inoreader订阅](https://www.inoreader.com/bundle/0014cd641489)

[部分安全相关公众号opml文件](https://www.inoreader.com/reader/api/0/bundle/opml/0014cd641489)

**Comment by firmianay** [comment]
加了，感谢大佬
